import type { Metadata } from "next";
//import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Layout from "@/components/Layout";
import Footer from "@/components/footer/Footer";
type Props={
  children?:React.ReactNode;
  
}

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "FKM Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}:Props) {
  return (
    <html lang="en">
      <body
       className="max-w-[1440px] m-auto font-serif"
      >
          
        <Layout>
        <Navbar/>
        {children}
        <Footer/>
        </Layout>
      </body>
    </html>
  );
}
